name: CI
on:
    push:
        branches:
            - step6
    pull_request:
        branches:
            - step6
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: 'temurin'

            - name: Test consumer tests
              run: ./gradlew consumer:test
            - name: Test consumer pact tests
              run: ./gradlew consumer:test --tests '*Pact*Test'
            - name: Copy consumer pacts
              run: ./gradlew consumer:copyPacts
            - name: Test provider pact tests
              run: ./gradlew provider:test --tests '*Pact*Test' || true